-- Privacy policy (2026-10-07), written for what the store actually collects: order / account /
-- contact / waitlist / return data, one sign-in cookie, bag + language + guest wishlist in
-- localStorage, Google Fonts, cash on delivery. Only replaces the seed placeholder, so a policy
-- already edited in Admin → Content is kept. Format: "## " heading, "- " bullet (InfoPage.tsx).

UPDATE pages SET body_en = CONCAT(
  'This policy explains what personal data VOID collects when you use this website, why we need it, who we share it with and the choices you have. If you have any questions, send us a message from our Contact page.\n\n',
  '## Who we are\n',
  'This website is run by VOID, a streetwear brand based in Egypt. We are responsible for the personal data collected through it. This policy covers this website only — sites we link to, such as Instagram and TikTok, have their own privacy policies.\n\n',
  '## What we collect\n',
  '- Order details: your name, mobile number, email and delivery address, what you ordered, and any note you leave at checkout.\n',
  '- Account details, if you create one: your name, email, mobile number, saved addresses, order history and wishlist. Your password is stored as a one-way hash, so nobody — including us — can read it.\n',
  '- Messages and waitlist sign-ups: what you send us from the Contact page, and your name, mobile number and (optional) email if you join the waitlist while the store is closed.\n',
  '- Exchange and refund requests: the pieces, the reason and the note you add, plus any photos you send us.\n',
  '- Technical data: what every website receives, such as your IP address and browser type, used only to keep the site running and secure.\n\n',
  'We never see or store your card details. Orders are currently paid cash on delivery; if we add online payment, you’ll enter your card details on the payment provider’s secure page, not on ours.\n\n',
  '## How we use it\n',
  '- To confirm, prepare, deliver and track your orders, and to handle exchanges and refunds.\n',
  '- To email you about your order and your account — for example an order confirmation, a status update or a password reset.\n',
  '- To reply to your messages, and to let you know when the store reopens if you joined the waitlist.\n',
  '- To prevent fraud and abuse, such as repeated failed sign-in attempts.\n\n',
  'We don’t sell your data, and we don’t send you marketing messages you didn’t ask for.\n\n',
  '## Who we share it with\n',
  '- Delivery companies: the name, mobile number and address they need to deliver your order.\n',
  '- Service providers: the companies that host this website and send our emails, only as far as they need it to do that.\n',
  '- Payment providers: only if you pay online.\n',
  '- Authorities: when the law requires it.\n\n',
  '## Cookies and data on your device\n',
  'We don’t use advertising or tracking cookies. When you sign in, we set one essential cookie that keeps you signed in.\n\n',
  'Your browser also keeps a few things on your device so they’re still there next time: your bag, your language and, when you’re not signed in, your wishlist.\n\n',
  'The fonts on this site load from Google Fonts, so your browser connects to Google’s servers to download them.\n\n',
  'You can clear cookies and site data at any time from your browser settings. This empties your bag and saved wishlist and signs you out.\n\n',
  '## How long we keep it\n',
  'We keep order records for as long as we need them to deliver your order, handle exchanges and refunds, and meet our legal and accounting obligations. Account details stay until you ask us to delete your account. Contact messages and waitlist sign-ups are kept only as long as they’re useful for replying to you or telling you the store is open.\n\n',
  '## Your rights\n',
  '- Access: ask whether we hold data about you and get a copy of it.\n',
  '- Correction: ask us to fix data that is wrong or incomplete. With an account, you can edit your saved addresses yourself.\n',
  '- Deletion: ask us to delete your data. We may have to keep some order records when the law requires it.\n',
  '- Opting out: ask us to stop contacting you at any time — for example, to take you off the waitlist.\n',
  '- Cookies: block or delete cookies from your browser settings.\n\n',
  'To use any of these rights, send us a message from our Contact page.\n\n',
  '## Keeping your data safe\n',
  'Every page is served over an encrypted connection (HTTPS), passwords are stored only as hashes, and access to customer data is limited to the team members who need it to run the store.\n\n',
  '## Changes to this policy\n',
  'We may update this policy when the store changes. The latest version is always on this page.'
) WHERE slug = 'privacy' AND body_en = '[PRIVACY POLICY]';

UPDATE pages SET body_ar = CONCAT(
  'السياسة دي بتوضّح البيانات الشخصية اللي VOID بتجمعها لما تستخدم الموقع، وبنحتاجها ليه، وبنشاركها مع مين، والاختيارات المتاحة ليك. لو عندك أي سؤال، ابعتلنا رسالة من صفحة «تواصل معنا».\n\n',
  '## مين إحنا\n',
  'الموقع ده بتديره VOID، براند ستريت وير من مصر، وإحنا المسؤولين عن البيانات الشخصية اللي بتتجمع من خلاله. السياسة دي بتغطي الموقع ده بس — المواقع اللي بنحط لينكاتها، زي إنستجرام وتيك توك، ليها سياسات خصوصية خاصة بيها.\n\n',
  '## البيانات اللي بنجمعها\n',
  '- بيانات الطلب: اسمك ورقم موبايلك وإيميلك وعنوان التوصيل، والقطع اللي طلبتها، وأي ملاحظة بتكتبها وإنت بتكمّل الطلب.\n',
  '- بيانات الحساب، لو عملت حساب: اسمك وإيميلك ورقم موبايلك وعناوينك المحفوظة وطلباتك السابقة وقائمة المفضلة. الباسورد بيتحفظ متشفّر بطريقة مينفعش ترجع، يعني محدش يقدر يقراه — ولا حتى إحنا.\n',
  '- الرسائل وقائمة الانتظار: اللي بتبعته لنا من صفحة «تواصل معنا»، واسمك ورقم موبايلك وإيميلك (اختياري) لو سجّلت في قائمة الانتظار والمتجر مقفول.\n',
  '- طلبات الاستبدال والاسترداد: القطع والسبب والملاحظة اللي بتكتبها، وأي صور بتبعتهالنا.\n',
  '- بيانات تقنية: اللي أي موقع بيستقبلها، زي عنوان الـ IP ونوع المتصفح، وبنستخدمها بس عشان الموقع يشتغل ويفضل آمن.\n\n',
  'إحنا مش بنشوف ولا بنحتفظ ببيانات الكارت بتاعك. الدفع حاليًا كاش عند الاستلام، ولو ضفنا الدفع أونلاين، هتكتب بيانات الكارت في صفحة شركة الدفع الآمنة، مش على موقعنا.\n\n',
  '## بنستخدمها في إيه\n',
  '- عشان نأكّد طلباتك ونجهّزها ونوصّلها ونتابعها، ونتعامل مع طلبات الاستبدال والاسترداد.\n',
  '- عشان نبعتلك إيميلات عن طلبك وحسابك — زي تأكيد الطلب أو تحديث حالته أو تغيير الباسورد.\n',
  '- عشان نرد على رسايلك، ونبلّغك لما المتجر يفتح تاني لو سجّلت في قائمة الانتظار.\n',
  '- عشان نمنع النصب وإساءة الاستخدام، زي محاولات تسجيل الدخول الغلط المتكررة.\n\n',
  'إحنا مش بنبيع بياناتك، ومش بنبعتلك رسايل تسويقية إنت مطلبتهاش.\n\n',
  '## بنشاركها مع مين\n',
  '- شركات الشحن: الاسم ورقم الموبايل والعنوان اللي محتاجينهم عشان يوصّلوا طلبك.\n',
  '- مقدّمي الخدمات: الشركات اللي بتستضيف الموقع وبتبعت الإيميلات بتاعتنا، وبس على قد ما يحتاجوا عشان يقدّموا الخدمة دي.\n',
  '- شركات الدفع: بس لو دفعت أونلاين.\n',
  '- الجهات الرسمية: لما القانون يلزمنا بكده.\n\n',
  '## الكوكيز والبيانات على جهازك\n',
  'مش بنستخدم كوكيز إعلانية أو كوكيز للتتبّع. لما تسجّل دخول، بنحط ملف كوكيز أساسي واحد بيخليك فاضل مسجّل.\n\n',
  'المتصفح بتاعك كمان بيحتفظ بشوية حاجات على جهازك عشان تلاقيها المرة الجاية: الحقيبة، واللغة اللي اخترتها، وقائمة المفضلة لو مش مسجّل دخول.\n\n',
  'الخطوط اللي على الموقع بتتحمّل من Google Fonts، فالمتصفح بيتصل بسيرفرات Google عشان ينزّلها.\n\n',
  'تقدر تمسح الكوكيز وبيانات الموقع في أي وقت من إعدادات المتصفح. ده هيفضّي الحقيبة وقائمة المفضلة المحفوظة ويسجّل خروجك.\n\n',
  '## بنحتفظ بيها لحد إمتى\n',
  'بنحتفظ بسجلات الطلبات طول ما محتاجينها عشان نوصّل طلبك ونتعامل مع الاستبدال والاسترداد ونلتزم بالمتطلبات القانونية والمحاسبية. بيانات الحساب بتفضل لحد ما تطلب مننا نمسح حسابك. ورسايل التواصل وبيانات قائمة الانتظار بنحتفظ بيها بس طول ما هي مفيدة عشان نرد عليك أو نبلّغك إن المتجر فتح.\n\n',
  '## حقوقك\n',
  '- حق الاطلاع: تسألنا لو عندنا بيانات عنك وتاخد نسخة منها.\n',
  '- حق التصحيح: تطلب مننا نصلّح أي بيانات غلط أو ناقصة. ولو عندك حساب، تقدر تعدّل عناوينك المحفوظة بنفسك.\n',
  '- حق الحذف: تطلب مننا نمسح بياناتك. ممكن نحتاج نحتفظ ببعض سجلات الطلبات لو القانون بيلزمنا بكده.\n',
  '- إيقاف التواصل: تطلب مننا نبطّل نتواصل معاك في أي وقت — زي إننا نشيلك من قائمة الانتظار.\n',
  '- الكوكيز: تقدر تمنع الكوكيز أو تمسحها من إعدادات المتصفح.\n\n',
  'عشان تستخدم أي حق من الحقوق دي، ابعتلنا رسالة من صفحة «تواصل معنا».\n\n',
  '## حماية بياناتك\n',
  'كل صفحات الموقع شغالة على اتصال متشفّر (HTTPS)، والباسوردات متحفظة متشفّرة بس، والوصول لبيانات العملاء مقصور على أعضاء الفريق اللي محتاجينها عشان يديروا المتجر.\n\n',
  '## التعديلات على السياسة دي\n',
  'ممكن نحدّث السياسة دي لما يحصل تغيير في المتجر، وهتلاقي آخر نسخة دايمًا في الصفحة دي.'
) WHERE slug = 'privacy' AND body_ar = '[سياسة الخصوصية]';
